#!/usr/bin/env bash
# clean-build-artifacts.sh — remove regeneratable build artifacts from this repo.
# Installed by ~/bin/github-clean-all.sh. Safe: NEVER deletes anything git tracks.
#@guard duration 60
#@guard approve Delete untracked build output (node_modules, bin, obj, dist, target, __pycache__, TestResults, coverage, .pytest_cache) under this checkout. Reversible: every deleted folder is regenerated by the next restore or build, and any folder containing a git-tracked file is skipped. A running build or gate in this checkout will fail mid-run.
#@guard warn Removing regeneratable build artifacts from the checkout. Tracked files are never deleted.
#@guard progress-bar id=clean-build-artifacts label="Clean Build Artifacts" color=grey

# Inside the execution gate: AI Mecca can warn, approve, deny and report progress. Run outside a
# chat (the nightly sweep, a terminal) the library's gate calls return at once and never prompt.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/common.sh"

# This script's own error policy, whatever the library set: one unreadable folder must not stop
# the sweep. Libraries that predate the progress helpers still get plain step/done lines.
set +e
set -uo pipefail
declare -F aimecca_step >/dev/null || aimecca_step() { printf '  %s\n' "$1"; }
declare -F aimecca_done >/dev/null || aimecca_done() {
  echo "#@guard progress id=${AIMECCA_PROGRESS_ID:-build} percent=100 color=green label=\"$1\" state=done fade=1000"
  printf '  %s\n' "$1"
}

ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
DRY=false
[[ "${1:-}" == "--dry-run" ]] && DRY=true
aimecca_step "[1/1] Removing regeneratable build artifacts..."
LOG="$HOME/Library/Logs/build-cleanup/$(basename "$ROOT").log"
mkdir -p "$(dirname "$LOG")"
count=0; freed_mb=0
while IFS= read -r -d "" d; do
  rel="${d#"$ROOT"/}"
  # SAFETY GUARD: skip if ANYTHING under this dir is tracked by git
  if [[ -n "$(git -C "$ROOT" ls-files -- "$rel/" 2>/dev/null | head -1)" ]]; then
    echo "[skip-git-tracked] $rel" >>"$LOG"
    continue
  fi
  mb=$(du -sm "$d" 2>/dev/null | cut -f1); mb=${mb:-0}
  if [[ "$DRY" == "true" ]]; then
    echo "[would-remove] $rel (${mb} MB)" >>"$LOG"
  else
    rm -rf "$d" && echo "[removed] $rel (${mb} MB)" >>"$LOG"
  fi
  count=$((count+1)); freed_mb=$((freed_mb+mb))
done < <(find "$ROOT" -type d \( -name node_modules -o -name bin -o -name obj \
      -o -name target -o -name dist -o -name __pycache__ -o -name TestResults \
      -o -name coverage -o -name .pytest_cache \) -not -path "*/.git/*" -prune -print0 2>/dev/null)
aimecca_done "$ROOT :: $count dirs, ${freed_mb} MB $( [[ "$DRY" == "true" ]] && echo '(dry-run)' )[ok]"
